package kiso

var Fields93 = []FieldDescription{
	MakeFieldDescription(0, "MTI", 4, FieldFormat_ASCII_N),
	MakeFieldDescription(1, "Bitmap", 8, FieldFormat_ASCII_Bitmap),
	MakeFieldDescription(2, "Primary account number", -19, FieldFormat_ASCII_N),
	MakeFieldDescription(3, "Processing code", 6, FieldFormat_ASCII_N),
	MakeFieldDescription(4, "Amount, transaction", 12, FieldFormat_ASCII_N),
	MakeFieldDescription(5, "Amount, reconciliation", 12, FieldFormat_ASCII_N),
	MakeFieldDescription(6, "Amount, cardholder billing", 12, FieldFormat_ASCII_N),
	MakeFieldDescription(7, "Date and time, transmission", 10, FieldFormat_ASCII_N),
	MakeFieldDescription(8, "Amount, cardholder billing fee", 8, FieldFormat_ASCII_N),
	MakeFieldDescription(9, "Conversion rate, reconciliation", 8, FieldFormat_ASCII_N),
	MakeFieldDescription(10, "Conversion rate, cardholder billing", 8, FieldFormat_ASCII_N),
	MakeFieldDescription(11, "Systems trace audit number", 6, FieldFormat_ASCII_N),
	MakeFieldDescription(12, "Date and time, local transaction", 12, FieldFormat_ASCII_N),
	MakeFieldDescription(13, "Date, effective", 4, FieldFormat_ASCII_N),
	MakeFieldDescription(14, "Date, expiration", 4, FieldFormat_ASCII_N),
	MakeFieldDescription(15, "Date, settlement", 6, FieldFormat_ASCII_N),
	MakeFieldDescription(16, "Date, conversion", 4, FieldFormat_ASCII_N),
	MakeFieldDescription(17, "Date, capture", 4, FieldFormat_ASCII_N),
	MakeFieldDescription(18, "Merchant type", 4, FieldFormat_ASCII_N),
	MakeFieldDescription(19, "Country code, acquiring institution", 3, FieldFormat_ASCII_N),
	MakeFieldDescription(20, "Country code, primary account number", 3, FieldFormat_ASCII_N),
	MakeFieldDescription(21, "Country code, forwarding institution", 3, FieldFormat_ASCII_N),
	MakeFieldDescription(22, "Point of service data code", 12, FieldFormat_AN),
	MakeFieldDescription(23, "Card sequence number", 3, FieldFormat_ASCII_N),
	MakeFieldDescription(24, "Function code", 3, FieldFormat_ASCII_N),
	MakeFieldDescription(25, "Message reason code", 4, FieldFormat_ASCII_N),
	MakeFieldDescription(26, "Card acceptor business code", 4, FieldFormat_ASCII_N),
	MakeFieldDescription(27, "Approval code length", 1, FieldFormat_ASCII_N),
	MakeFieldDescription(28, "Date, reconciliation", 6, FieldFormat_ASCII_N),
	MakeFieldDescription(29, "Reconciliation indicator", 3, FieldFormat_ASCII_N),
	MakeFieldDescription(30, "Amounts, original", 24, FieldFormat_ASCII_N),
	MakeFieldDescription(31, "Acquirer reference data", -99, FieldFormat_ANS),
	MakeFieldDescription(32, "Acquirer institution identification code", -11, FieldFormat_ASCII_N),
	MakeFieldDescription(33, "Forwarding institution identification code", -11, FieldFormat_ASCII_N),
	MakeFieldDescription(34, "Primary account number, extended", -28, FieldFormat_NS),
	MakeFieldDescription(35, "Track 2 data", -37, FieldFormat_ASCII_Z),
	MakeFieldDescription(36, "Track 3 data", -104, FieldFormat_ASCII_Z),
	MakeFieldDescription(37, "Retrieval reference number", 12, FieldFormat_ANP),
	MakeFieldDescription(38, "Approval code ", 6, FieldFormat_ANP),
	MakeFieldDescription(39, "Action code ", 3, FieldFormat_ASCII_N),
	MakeFieldDescription(40, "Service code ", 3, FieldFormat_ASCII_N),
	MakeFieldDescription(41, "Card acceptor terminal identification ", 8, FieldFormat_ANS),
	MakeFieldDescription(42, "Card acceptor identification code", 15, FieldFormat_ANS),
	MakeFieldDescription(43, "Card acceptor name/location", -99, FieldFormat_ANS),
	MakeFieldDescription(44, "Additional response data", -99, FieldFormat_ANS),
	MakeFieldDescription(45, "Track 1 data", -76, FieldFormat_ANS),
	MakeFieldDescription(46, "Amounts, fees", -204, FieldFormat_ANS),
	MakeFieldDescription(47, "Additional data - national", -999, FieldFormat_ANS),
	MakeFieldDescription(48, "Additional data - private", -999, FieldFormat_ANS),
	MakeFieldDescription(49, "Currency code, transaction", 3, FieldFormat_ASCII_N),
	MakeFieldDescription(50, "Currency code, reconciliation", 3, FieldFormat_ASCII_N),
	MakeFieldDescription(51, "Currency code, cardholder billing", 3, FieldFormat_ASCII_N),
	MakeFieldDescription(52, "Personal identification number (PIN) data", 8, FieldFormat_ASCII_B),
	MakeFieldDescription(53, "Security related control information", -48, FieldFormat_ASCII_B),
	MakeFieldDescription(54, "Amounts, additional", -120, FieldFormat_ANS),
	MakeFieldDescription(55, "Integrated circuit card system related data", -255, FieldFormat_ASCII_B),
	MakeFieldDescription(56, "Original data elements", -35, FieldFormat_ASCII_N),
	MakeFieldDescription(57, "Authorization life cycle code", 3, FieldFormat_ASCII_N),
	MakeFieldDescription(58, "Authorizing agent institution identification code", -11, FieldFormat_ASCII_N),
	MakeFieldDescription(59, "Transport data", -999, FieldFormat_ANS),
	MakeFieldDescription(60, "Reserved for national use", -999, FieldFormat_ANS),
	MakeFieldDescription(61, "Reserved for national use", -999, FieldFormat_ANS),
	MakeFieldDescription(62, "Reserved for private use", -999, FieldFormat_ANS),
	MakeFieldDescription(63, "Reserved for private use", -999, FieldFormat_ANS),
	MakeFieldDescription(64, "Message authentication code field", 8, FieldFormat_ASCII_B),
	MakeFieldDescription(65, "Reserved for ISO use", 8, FieldFormat_ASCII_B),
	MakeFieldDescription(66, "Amounts, original fees", -204, FieldFormat_ANS),
	MakeFieldDescription(67, "Extended payment data", 2, FieldFormat_ASCII_N),
	MakeFieldDescription(68, "Country code, receiving institution ", 3, FieldFormat_ASCII_N),
	MakeFieldDescription(69, "Country code, settlement institution", 3, FieldFormat_ASCII_N),
	MakeFieldDescription(70, "Country code, authorizing agent institution", 3, FieldFormat_ASCII_N),
	MakeFieldDescription(71, "Message number", 8, FieldFormat_ASCII_N),
	MakeFieldDescription(72, "Data record", -999, FieldFormat_ANS),
	MakeFieldDescription(73, "Date, action", 6, FieldFormat_ASCII_N),
	MakeFieldDescription(74, "Credits, number", 10, FieldFormat_ASCII_N),
	MakeFieldDescription(75, "Credits, reversal number", 10, FieldFormat_ASCII_N),
	MakeFieldDescription(76, "Debits, number", 10, FieldFormat_ASCII_N),
	MakeFieldDescription(77, "Debits, reversal number", 10, FieldFormat_ASCII_N),
	MakeFieldDescription(78, "Transfer, number", 10, FieldFormat_ASCII_N),
	MakeFieldDescription(79, "Transfer, reversal number ", 10, FieldFormat_ASCII_N),
	MakeFieldDescription(80, "Inquiries, number ", 10, FieldFormat_ASCII_N),
	MakeFieldDescription(81, "Authorizations, number ", 10, FieldFormat_ASCII_N),
	MakeFieldDescription(82, "Inquiries, reversal number", 10, FieldFormat_ASCII_N),
	MakeFieldDescription(83, "Payments, number", 10, FieldFormat_ASCII_N),
	MakeFieldDescription(84, "Payments, reversal number", 10, FieldFormat_ASCII_N),
	MakeFieldDescription(85, "Fee collections, number", 10, FieldFormat_ASCII_N),
	MakeFieldDescription(86, "Credits, amount", 16, FieldFormat_ASCII_N),
	MakeFieldDescription(87, "Credits, reversal amount", 16, FieldFormat_ASCII_N),
	MakeFieldDescription(88, "Debits, amount", 16, FieldFormat_ASCII_N),
	MakeFieldDescription(89, "Debits, reversal amount", 16, FieldFormat_ASCII_N),
	MakeFieldDescription(90, "Authorizations, reversal number", 10, FieldFormat_ASCII_N),
	MakeFieldDescription(91, "Country code, transaction destination institution", 3, FieldFormat_ASCII_N),
	MakeFieldDescription(92, "Country code, transaction originator institution", 3, FieldFormat_ASCII_N),
	MakeFieldDescription(93, "Transaction destination institution identification code", -11, FieldFormat_ASCII_N),
	MakeFieldDescription(94, "Transaction originator institution identification code ", -11, FieldFormat_ASCII_N),
	MakeFieldDescription(95, "Card issuer reference data", -99, FieldFormat_ANS),
	MakeFieldDescription(96, "Key management data", -999, FieldFormat_ASCII_B),
	MakeFieldDescription(97, "Amount, net reconciliation", 17, FieldFormat_ASCII_N),
	MakeFieldDescription(98, "Payee", 25, FieldFormat_ANS),
	MakeFieldDescription(99, "Settlement institution identification code", -11, FieldFormat_AN),
	MakeFieldDescription(100, "Receiving institution identification code", -11, FieldFormat_ASCII_N),
	MakeFieldDescription(101, "File name", -17, FieldFormat_ANS),
	MakeFieldDescription(102, "Account identification 1", -28, FieldFormat_ANS),
	MakeFieldDescription(103, "Account identification 2", -28, FieldFormat_ANS),
	MakeFieldDescription(104, "Transaction description", -100, FieldFormat_ANS),
	MakeFieldDescription(105, "Credits, chargeback amount", 16, FieldFormat_ASCII_N),
	MakeFieldDescription(106, "Debits, chargeback amount", 16, FieldFormat_ASCII_N),
	MakeFieldDescription(107, "Credits, chargeback number", 10, FieldFormat_ASCII_N),
	MakeFieldDescription(108, "Debits, chargeback number", 10, FieldFormat_ASCII_N),
	MakeFieldDescription(109, "Credits, fee amounts", -84, FieldFormat_ANS),
	MakeFieldDescription(110, "Debits, fee amounts", -84, FieldFormat_ANS),
	MakeFieldDescription(111, "Reserved for IS0 use", -999, FieldFormat_ANS),
	MakeFieldDescription(112, "Reserved for IS0 use", -999, FieldFormat_ANS),
	MakeFieldDescription(113, "Reserved for IS0 use", -999, FieldFormat_ANS),
	MakeFieldDescription(114, "Reserved for IS0 use", -999, FieldFormat_ANS),
	MakeFieldDescription(115, "Reserved for IS0 use", -999, FieldFormat_ANS),
	MakeFieldDescription(116, "Reserved for national use", -999, FieldFormat_ANS),
	MakeFieldDescription(117, "Reserved for national use", -999, FieldFormat_ANS),
	MakeFieldDescription(118, "Reserved for national use", -999, FieldFormat_ANS),
	MakeFieldDescription(119, "Reserved for national use", -999, FieldFormat_ANS),
	MakeFieldDescription(120, "Reserved for national use", -999, FieldFormat_ANS),
	MakeFieldDescription(121, "Reserved for national use", -999, FieldFormat_ANS),
	MakeFieldDescription(122, "Reserved for national use", -999, FieldFormat_ANS),
	MakeFieldDescription(123, "Reserved for KISO use", -999, FieldFormat_ANS),
	MakeFieldDescription(124, "Reserved for private use", -999, FieldFormat_ANS),
	MakeFieldDescription(125, "Reserved for private use", -999, FieldFormat_ANS),
	MakeFieldDescription(126, "Reserved for private use", -999, FieldFormat_ANS),
	MakeFieldDescription(127, "Reserved for private use", -999, FieldFormat_ANS),
	MakeFieldDescription(128, "Message authentication code field", 8, FieldFormat_ASCII_B),
}
